name: PhotoPuzzle
options:
  bundleIdPrefix: com.idreamstudio
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.0"
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 11.0.0
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: YES
    OTHER_LDFLAGS: "$(inherited)"


targets:
  PhotoPuzzle:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    bundleId: com.idreamstudio.photopuzzle
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: PhotoPuzzle
        UILaunchStoryboardName: LaunchScreen
        GADApplicationIdentifier: ca-app-pub-3940256099942544~1458002511
        NSCameraUsageDescription: "We need access to your camera to take photos for puzzles."
        NSPhotoLibraryUsageDescription: "We need access to your photos so you can create puzzles from your images."
        NSPhotoLibraryAddUsageDescription: "We may save puzzle images to your library when you share."
        NSUserTrackingUsageDescription: "Your data may be used to deliver personalized ads."
    sources:
      - Sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: GoogleMobileAds
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.idreamstudio.photopuzzle
